import { randomBytes } from '@noble/hashes/utils.js';
import { isProbablePrime } from './primality.ts';
import {
  bytesToNumber,
  ensureBytes,
  getFieldBytesLength,
  getMinHashLength,
  mapHashToField,
  numberToBytesBE,
  pow,
  type TArg,
  type TRet,
} from './utils.ts';

const _0n = /* @__PURE__ */ BigInt(0);
const _1n = /* @__PURE__ */ BigInt(1);
const _2n = /* @__PURE__ */ BigInt(2);

/** Classic finite-field Diffie-Hellman group parameters. */
export type DHGroup = {
  /** Finite-field prime modulus for the DH group. */
  p: bigint;
  /** Prime order of the subgroup generated by `g`. */
  q: bigint;
  /** Generator of the prime-order subgroup. */
  g: bigint;
};

/** Legacy custom DH parameters without an authenticated subgroup order. */
export type UnsafeDHGroup = {
  /** Finite-field modulus used by the legacy group. */
  p: bigint;
  /** Generator whose order is not validated. */
  g: bigint;
  /** Safe custom groups must use {@link DHGroup} instead. */
  q?: never;
};

const group = (p: bigint, g: bigint): Readonly<DHGroup> =>
  /* @__PURE__ */ Object.freeze({ p, q: (p - _1n) / _2n, g });

/** Short names of the modern built-in MODP groups. */
export type DHGroupName = 'modp14' | 'modp15' | 'modp16' | 'modp17' | 'modp18';
/** Short names of the obsolete built-in MODP groups. */
export type LegacyDHGroupName = 'modp1' | 'modp2' | 'modp5';
/** Options controlling access to obsolete built-in groups. */
export type DHOptions = {
  /** Explicitly allow obsolete built-in groups. Never enable this for new protocols. */
  allowUnsafeLegacy?: boolean;
  /** Restore unvalidated `{ p, g }` custom groups and their historical key ranges. */
  unsafeAllowUnvalidatedGroup?: boolean;
};
/** Required opt-in for an obsolete built-in group. */
export type UnsafeLegacyDHOptions = {
  /** Explicit acknowledgement that the selected legacy group is unsafe. */
  allowUnsafeLegacy: true;
  /** Legacy named groups do not require the custom-group compatibility mode. */
  unsafeAllowUnvalidatedGroup?: boolean;
};
/** Required opt-in for a custom group without a validated subgroup order. */
export type UnsafeCustomDHOptions = {
  /** Explicit acknowledgement that custom parameters and peer membership are not validated. */
  unsafeAllowUnvalidatedGroup: true;
  /** Obsolete named groups still require their separate opt-in. */
  allowUnsafeLegacy?: boolean;
};
type DHApi = {
  randomPrivateKey(): Uint8Array;
  getPublicKey(privateKey: Uint8Array): Uint8Array;
  getSharedSecret(privateA: Uint8Array, publicB: Uint8Array): Uint8Array;
};

type ValidatedDHGroup = { p: bigint; q: bigint; g: bigint };
const DH_VALIDATION_CACHE_SIZE = 16;
const validatedDHGroups: ValidatedDHGroup[] = [];

// isProbablePrime() performs these random Miller-Rabin rounds and then a Lucas test.
// Use the same FIPS-style assurance levels as the package's DSA/RSA validation:
// large prime candidates need few expensive rounds, while short q values need more.
const dhPrimeIterations = (bits: number): number => {
  if (bits > 1536) return 4;
  if (bits >= 1024) return 5;
  if (bits === 224) return 24;
  return 27;
};

function validateCustomGroup(group: DHGroup): void {
  const { p, q, g } = group;
  if (validatedDHGroups.some((valid) => valid.p === p && valid.q === q && valid.g === g)) return;
  if (typeof p !== 'bigint' || typeof q !== 'bigint' || typeof g !== 'bigint')
    throw new Error('DH: wrong group params');
  const pBits = p.toString(2).length;
  const qBits = q.toString(2).length;
  if (pBits < 2048 || qBits < 224 || pBits > 16384 || qBits >= pBits)
    throw new Error('DH: weak or oversized custom group');
  if (g <= _1n || g >= p - _1n || (p - _1n) % q !== _0n)
    throw new Error('DH: invalid custom subgroup');
  if (
    !isProbablePrime(q, dhPrimeIterations(qBits)) ||
    !isProbablePrime(p, dhPrimeIterations(pBits))
  )
    throw new Error('DH: non-prime custom group');
  if (pow(g, q, p) !== _1n) throw new Error('DH: invalid custom subgroup');
  validatedDHGroups.push({ p, q, g });
  if (validatedDHGroups.length > DH_VALIDATION_CACHE_SIZE) validatedDHGroups.shift();
}

/**
 * Obsolete built-in MODP groups retained for explicit legacy compatibility.
 * @example
 * Opt in only when interoperating with an existing legacy protocol.
 * ```ts
 * import { DH, LegacyDHGroups } from 'micro-rsa-dsa-dh/dh.js';
 * const group = LegacyDHGroups.modp5;
 * const dh = DH(group, { allowUnsafeLegacy: true });
 * const privateKey = dh.randomPrivateKey();
 * privateKey;
 * ```
 */
export const LegacyDHGroups: Readonly<Record<LegacyDHGroupName, Readonly<DHGroup>>> =
  /* @__PURE__ */ (() =>
    Object.freeze({
      modp1: group(
        BigInt(
          '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
            '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
            'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
            'e485b576625e7ec6f44c42e9a63a3620ffffffffffffffff'
        ),
        _2n
      ),
      modp2: group(
        BigInt(
          '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
            '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
            'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
            'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
            'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece65381' +
            'ffffffffffffffff'
        ),
        _2n
      ),
      modp5: group(
        BigInt(
          '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
            '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
            'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
            'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
            'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
            'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
            '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
            '670c354e4abc9804f1746c08ca237327ffffffffffffffff'
        ),
        _2n
      ),
    }))();

/**
 * Modern built-in MODP groups keyed by their short names.
 * RFC 3526 §§3-7: these property names follow the IKE group numbers for
 * the published MODP parameters. Every included modulus is at least 2048 bits.
 * @example
 * Pick one of the modern built-in MODP groups before deriving keys.
 * ```ts
 * import { DH, DHGroups } from 'micro-rsa-dsa-dh/dh.js';
 * const group = DHGroups.modp14;
 * const dh = DH(group);
 * const privateKey = dh.randomPrivateKey();
 * privateKey;
 * ```
 */
export const DHGroups: Readonly<Record<DHGroupName, Readonly<DHGroup>>> = /* @__PURE__ */ (() =>
  Object.freeze({
    modp14: group(
      BigInt(
        '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
          '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
          'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
          'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
          'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
          'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
          '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
          '670c354e4abc9804f1746c08ca18217c32905e462e36ce3b' +
          'e39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9' +
          'de2bcbf6955817183995497cea956ae515d2261898fa0510' +
          '15728e5a8aacaa68ffffffffffffffff'
      ),
      _2n
    ),
    modp15: group(
      BigInt(
        '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
          '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
          'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
          'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
          'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
          'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
          '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
          '670c354e4abc9804f1746c08ca18217c32905e462e36ce3b' +
          'e39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9' +
          'de2bcbf6955817183995497cea956ae515d2261898fa0510' +
          '15728e5a8aaac42dad33170d04507a33a85521abdf1cba64' +
          'ecfb850458dbef0a8aea71575d060c7db3970f85a6e1e4c7' +
          'abf5ae8cdb0933d71e8c94e04a25619dcee3d2261ad2ee6b' +
          'f12ffa06d98a0864d87602733ec86a64521f2b18177b200c' +
          'bbe117577a615d6c770988c0bad946e208e24fa074e5ab31' +
          '43db5bfce0fd108e4b82d120a93ad2caffffffffffffffff'
      ),
      _2n
    ),
    modp16: group(
      BigInt(
        '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
          '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
          'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
          'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
          'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
          'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
          '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
          '670c354e4abc9804f1746c08ca18217c32905e462e36ce3b' +
          'e39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9' +
          'de2bcbf6955817183995497cea956ae515d2261898fa0510' +
          '15728e5a8aaac42dad33170d04507a33a85521abdf1cba64' +
          'ecfb850458dbef0a8aea71575d060c7db3970f85a6e1e4c7' +
          'abf5ae8cdb0933d71e8c94e04a25619dcee3d2261ad2ee6b' +
          'f12ffa06d98a0864d87602733ec86a64521f2b18177b200c' +
          'bbe117577a615d6c770988c0bad946e208e24fa074e5ab31' +
          '43db5bfce0fd108e4b82d120a92108011a723c12a787e6d7' +
          '88719a10bdba5b2699c327186af4e23c1a946834b6150bda' +
          '2583e9ca2ad44ce8dbbbc2db04de8ef92e8efc141fbecaa6' +
          '287c59474e6bc05d99b2964fa090c3a2233ba186515be7ed' +
          '1f612970cee2d7afb81bdd762170481cd0069127d5b05aa9' +
          '93b4ea988d8fddc186ffb7dc90a6c08f4df435c934063199' +
          'ffffffffffffffff'
      ),
      _2n
    ),
    modp17: group(
      BigInt(
        '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
          '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
          'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
          'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
          'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
          'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
          '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
          '670c354e4abc9804f1746c08ca18217c32905e462e36ce3b' +
          'e39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9' +
          'de2bcbf6955817183995497cea956ae515d2261898fa0510' +
          '15728e5a8aaac42dad33170d04507a33a85521abdf1cba64' +
          'ecfb850458dbef0a8aea71575d060c7db3970f85a6e1e4c7' +
          'abf5ae8cdb0933d71e8c94e04a25619dcee3d2261ad2ee6b' +
          'f12ffa06d98a0864d87602733ec86a64521f2b18177b200c' +
          'bbe117577a615d6c770988c0bad946e208e24fa074e5ab31' +
          '43db5bfce0fd108e4b82d120a92108011a723c12a787e6d7' +
          '88719a10bdba5b2699c327186af4e23c1a946834b6150bda' +
          '2583e9ca2ad44ce8dbbbc2db04de8ef92e8efc141fbecaa6' +
          '287c59474e6bc05d99b2964fa090c3a2233ba186515be7ed' +
          '1f612970cee2d7afb81bdd762170481cd0069127d5b05aa9' +
          '93b4ea988d8fddc186ffb7dc90a6c08f4df435c934028492' +
          '36c3fab4d27c7026c1d4dcb2602646dec9751e763dba37bd' +
          'f8ff9406ad9e530ee5db382f413001aeb06a53ed9027d831' +
          '179727b0865a8918da3edbebcf9b14ed44ce6cbaced4bb1b' +
          'db7f1447e6cc254b332051512bd7af426fb8f401378cd2bf' +
          '5983ca01c64b92ecf032ea15d1721d03f482d7ce6e74fef6' +
          'd55e702f46980c82b5a84031900b1c9e59e7c97fbec7e8f3' +
          '23a97a7e36cc88be0f1d45b7ff585ac54bd407b22b4154aa' +
          'cc8f6d7ebf48e1d814cc5ed20f8037e0a79715eef29be328' +
          '06a1d58bb7c5da76f550aa3d8a1fbff0eb19ccb1a313d55c' +
          'da56c9ec2ef29632387fe8d76e3c0468043e8f663f4860ee' +
          '12bf2d5b0b7474d6e694f91e6dcc4024ffffffffffffffff'
      ),
      _2n
    ),
    modp18: group(
      BigInt(
        '0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd1' +
          '29024e088a67cc74020bbea63b139b22514a08798e3404dd' +
          'ef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245' +
          'e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7ed' +
          'ee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3d' +
          'c2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f' +
          '83655d23dca3ad961c62f356208552bb9ed529077096966d' +
          '670c354e4abc9804f1746c08ca18217c32905e462e36ce3b' +
          'e39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9' +
          'de2bcbf6955817183995497cea956ae515d2261898fa0510' +
          '15728e5a8aaac42dad33170d04507a33a85521abdf1cba64' +
          'ecfb850458dbef0a8aea71575d060c7db3970f85a6e1e4c7' +
          'abf5ae8cdb0933d71e8c94e04a25619dcee3d2261ad2ee6b' +
          'f12ffa06d98a0864d87602733ec86a64521f2b18177b200c' +
          'bbe117577a615d6c770988c0bad946e208e24fa074e5ab31' +
          '43db5bfce0fd108e4b82d120a92108011a723c12a787e6d7' +
          '88719a10bdba5b2699c327186af4e23c1a946834b6150bda' +
          '2583e9ca2ad44ce8dbbbc2db04de8ef92e8efc141fbecaa6' +
          '287c59474e6bc05d99b2964fa090c3a2233ba186515be7ed' +
          '1f612970cee2d7afb81bdd762170481cd0069127d5b05aa9' +
          '93b4ea988d8fddc186ffb7dc90a6c08f4df435c934028492' +
          '36c3fab4d27c7026c1d4dcb2602646dec9751e763dba37bd' +
          'f8ff9406ad9e530ee5db382f413001aeb06a53ed9027d831' +
          '179727b0865a8918da3edbebcf9b14ed44ce6cbaced4bb1' +
          'bdb7f1447e6cc254b332051512bd7af426fb8f401378cd2' +
          'bf5983ca01c64b92ecf032ea15d1721d03f482d7ce6e74f' +
          'ef6d55e702f46980c82b5a84031900b1c9e59e7c97fbec7' +
          'e8f323a97a7e36cc88be0f1d45b7ff585ac54bd407b22b4' +
          '154aacc8f6d7ebf48e1d814cc5ed20f8037e0a79715eef2' +
          '9be32806a1d58bb7c5da76f550aa3d8a1fbff0eb19ccb1a' +
          '313d55cda56c9ec2ef29632387fe8d76e3c0468043e8f66' +
          '3f4860ee12bf2d5b0b7474d6e694f91e6dbe115974a3926' +
          'f12fee5e438777cb6a932df8cd8bec4d073b931ba3bc832' +
          'b68d9dd300741fa7bf8afc47ed2576f6936ba424663aab6' +
          '39c5ae4f5683423b4742bf1c978238f16cbe39d652de3fd' +
          'b8befc848ad922222e04a4037c0713eb57a81a23f0c7347' +
          '3fc646cea306b4bcbc8862f8385ddfa9d4b7fa2c087e879' +
          '683303ed5bdd3a062b3cf5b3a278a66d2a13f83f44f82dd' +
          'f310ee074ab6a364597e899a0255dc164f31cc50846851d' +
          'f9ab48195ded7ea1b1d510bd7ee74d73faf36bc31ecfa26' +
          '8359046f4eb879f924009438b481c6cd7889a002ed5ee38' +
          '2bc9190da6fc026e479558e4475677e9aa9e3050e276569' +
          '4dfc81f56e880b96e7160c980dd98edd3dfffffffffffff' +
          'ffff'
      ),
      _2n
    ),
  }))();

/**
 * Basic Diffie Hellman implementation with focus on simplicity.
 * For now: non-constant time operations, no precomputes.
 *
 * We can speed up operations the same way as in `@noble/curves`,
 * but if re-key happens often it could be slow.
 * @param group - Modern group name, validated `{ p, q, g }` parameters, or an opted-in unsafe
 *   group.
 * @param options - Group options. See {@link DHOptions}; legacy and unvalidated custom groups
 *   require their corresponding explicit unsafe options.
 * @returns Diffie-Hellman helpers for key generation and shared-secret derivation.
 * @throws On wrong option types. {@link TypeError}
 * @throws If the group selector or supplied group parameters are invalid. {@link Error}
 * @example
 * Derive the same shared secret on both sides of a modern named group.
 * ```ts
 * import { deepStrictEqual } from 'node:assert';
 * import { DH } from 'micro-rsa-dsa-dh/dh.js';
 * const dh = DH('modp14');
 * const alice = dh.randomPrivateKey();
 * const bob = dh.randomPrivateKey();
 * const alicePub = dh.getPublicKey(alice);
 * const bobPub = dh.getPublicKey(bob);
 * deepStrictEqual(dh.getSharedSecret(alice, bobPub), dh.getSharedSecret(bob, alicePub));
 * ```
 */
export function DH(group: DHGroupName | DHGroup, options?: DHOptions): TRet<DHApi>;
export function DH(group: LegacyDHGroupName, options: UnsafeLegacyDHOptions): TRet<DHApi>;
export function DH(group: UnsafeDHGroup, options: UnsafeCustomDHOptions): TRet<DHApi>;
export function DH(
  group: DHGroupName | LegacyDHGroupName | DHGroup | UnsafeDHGroup,
  options: DHOptions = {}
): TRet<DHApi> {
  if (options === null || typeof options !== 'object' || Array.isArray(options))
    throw new TypeError('DH: options should be object');
  const { allowUnsafeLegacy, unsafeAllowUnvalidatedGroup } = options;
  if (allowUnsafeLegacy !== undefined && typeof allowUnsafeLegacy !== 'boolean')
    throw new TypeError('DH: allowUnsafeLegacy should be boolean');
  if (unsafeAllowUnvalidatedGroup !== undefined && typeof unsafeAllowUnvalidatedGroup !== 'boolean')
    throw new TypeError('DH: unsafeAllowUnvalidatedGroup should be boolean');
  let selected: DHGroup | UnsafeDHGroup | undefined;
  let isLegacy = false;
  let isModernBuiltIn = false;
  if (typeof group === 'string') {
    if (Object.prototype.hasOwnProperty.call(DHGroups, group)) {
      selected = DHGroups[group as DHGroupName];
      isModernBuiltIn = true;
    } else if (Object.prototype.hasOwnProperty.call(LegacyDHGroups, group)) {
      selected = LegacyDHGroups[group as LegacyDHGroupName];
      isLegacy = true;
    }
  } else {
    selected = group;
    isLegacy =
      (group.p === LegacyDHGroups.modp1.p && group.g === LegacyDHGroups.modp1.g) ||
      (group.p === LegacyDHGroups.modp2.p && group.g === LegacyDHGroups.modp2.g) ||
      (group.p === LegacyDHGroups.modp5.p && group.g === LegacyDHGroups.modp5.g);
    isModernBuiltIn = (Object.keys(DHGroups) as DHGroupName[]).some((name) => {
      const known = DHGroups[name];
      return group.p === known.p && group.g === known.g && group.q === known.q;
    });
  }
  if (!selected) throw new Error('DH: wrong group');
  if (isLegacy && allowUnsafeLegacy !== true)
    throw new Error('DH: legacy group requires { allowUnsafeLegacy: true }');
  const unsafeCustom = !isLegacy && !isModernBuiltIn && unsafeAllowUnvalidatedGroup === true;
  if (!isLegacy && !isModernBuiltIn && !unsafeCustom) {
    if (!('q' in selected) || typeof selected.q !== 'bigint')
      throw new Error('DH: custom group requires q or { unsafeAllowUnvalidatedGroup: true }');
    validateCustomGroup(selected as DHGroup);
  }
  const unsafeMode = isLegacy || unsafeCustom;
  const { p, g } = selected;
  if (typeof p !== 'bigint' || typeof g !== 'bigint') throw new Error('DH: wrong group params');
  const q = unsafeMode ? undefined : (selected as DHGroup).q;
  if (q !== undefined && typeof q !== 'bigint') throw new Error('DH: wrong group params');
  const bytesLen = getFieldBytesLength(p);
  // Interval endpoints for key validation, hoisted out of the per-call helpers.
  const pm1 = p - _1n;
  const pm2 = p - _2n;
  const privateMax = q === undefined ? pm2 : q - _2n;
  const validatedPublicKeys: bigint[] = [];
  const cachePublicKey = (publicKey: bigint): void => {
    if (q === undefined || validatedPublicKeys.includes(publicKey)) return;
    validatedPublicKeys.push(publicKey);
    if (validatedPublicKeys.length > 16) validatedPublicKeys.shift();
  };
  const privateKeyNum = (key: TArg<Uint8Array>) => {
    const priv = bytesToNumber(ensureBytes('private key', key, bytesLen));
    // Validated groups use the subgroup interval [2, q-2]. Explicit unsafe
    // compatibility retains the historical [2, p-2] interval.
    if (priv < _2n || priv > privateMax) throw new Error('DH: invalid private key');
    return priv;
  };
  const publicKeyNum = (key: TArg<Uint8Array>) => {
    const pub = bytesToNumber(ensureBytes('public key', key, bytesLen));
    // RFC 7919 §5.1: FFDHE peers MUST validate public keys with "1 < Y < p-1".
    // RFC 2631 §2.1.5 and RFC 2785 §3.1 also reject received public keys outside [2, p-1];
    // excluding p-1 follows the stricter FFDHE endpoint check and matches Node crypto.
    if (pub < _2n || pub >= pm1) throw new Error('DH: invalid public key');
    if (q !== undefined && !validatedPublicKeys.includes(pub)) {
      if (pow(pub, q, p) !== _1n) throw new Error('DH: public key outside subgroup');
      cachePublicKey(pub);
    }
    return pub;
  };
  return {
    randomPrivateKey(): TRet<Uint8Array> {
      const order = q ?? p;
      const scalar = mapHashToField(randomBytes(getMinHashLength(order)), order, _2n);
      // Preserve the historical fixed-p-width private-key encoding even when q is much smaller.
      return numberToBytesBE(bytesToNumber(scalar), bytesLen);
    },
    getPublicKey(privateKey: TArg<Uint8Array>): TRet<Uint8Array> {
      const privNum = privateKeyNum(privateKey);
      const n = pow(g, privNum, p); // g^privateKey mod p
      cachePublicKey(n); // Locally generated public keys are in the validated g subgroup.
      // Public keys must stay fixed-width so they can round-trip into getSharedSecret()
      // even when the modular exponentiation result has leading zero bytes.
      return numberToBytesBE(n, bytesLen);
    },
    getSharedSecret(privateA: TArg<Uint8Array>, publicB: TArg<Uint8Array>): TRet<Uint8Array> {
      const privNum = privateKeyNum(privateA);
      const pubNum = publicKeyNum(publicB);
      const n = pow(pubNum, privNum, p); // publicB^privateA mod p
      return numberToBytesBE(n, bytesLen);
    },
  };
}

/**
 * Alias for `DH()`.
 * @param group - Modern group name, validated parameters, or an opted-in unsafe group.
 * @param options - Group options. See {@link DHOptions}; unsafe groups require explicit opt-in.
 * @returns Diffie-Hellman helpers for key generation and shared-secret derivation.
 * @example
 * Use the friendlier alias for the same DH helper.
 * ```ts
 * import { deepStrictEqual } from 'node:assert';
 * import { diffieHellman } from 'micro-rsa-dsa-dh/dh.js';
 * const dh = diffieHellman('modp14');
 * const alice = dh.randomPrivateKey();
 * const bob = dh.randomPrivateKey();
 * const alicePub = dh.getPublicKey(alice);
 * const bobPub = dh.getPublicKey(bob);
 * deepStrictEqual(dh.getSharedSecret(alice, bobPub), dh.getSharedSecret(bob, alicePub));
 * ```
 */
export const diffieHellman: typeof DH = DH;
